dist: bionic
language: cpp

compiler:
  - gcc

addons:
  sonarcloud:
    organization: "saemu"
    token:
      secure: "oRwQYbTBZ2NpMOF+SARBbp39E73t3xnUUX708S5RZ9IrHL9jewC15en1bFEWweCm8A2ydQ9bh5P4sny46EsQfEJQ7pMT0KrCN2+2tWooXMH+ZfNNDcbIwXduLQRaA4SY0QONr36jQ3q/C60W+ekiky09DfaQUgpVHUX8xr1xSranIDIzGdzoIkYe9qPYkNOe8jbZ2868JQkGeHhHdhAibUpwax1CAqM/pWkGFkFO/mt8CHoSb7pzuqCdkkabgH8nDHxuzS3Krnou62tZfyWt9ZUTj+e3XpTTtoEEm0Bt6dw168S77i5LNDgiy3OwhTkIAoHWBTxV36vRdqa0fSgV5uDAF7pcAxlzUWLyRo1LSbiGluk4iJX7rvud43Ut4ZoaEtQ7Z3VIi99ObSoD4Z0Ck6K1XdLOVJ8rT6jiOKBcN+PS5fqtrpxNv+YJrTnTzxQdX46p2tHH0WpWncCRs6u4NtW45KQoGKDgT8Ckv46Yp0C7V9pMFDyWphLtiCqHrDO6vzfhUHS5bi0tS9YWQaB8c1gQYyTdTdpt+KbtYsh2iaghBUehYjIlz3QI5wMLq+L7isVyEcb6ktMo6WAjEqZt/PLNnkBryW2bEPKmBGoi2wSSWm78oo74UlmplZbOKRlED2NBSq0+xFjZNvUPr010ulw8nzytBdJdLq9OSckKzJY="

install:
  # use latest CMake
  - |
    DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v3.16.3/cmake-3.16.3-Linux-x86_64.tar.gz"
    mkdir -p ${DEPS_DIR}/cmake
    travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  # Install conan
  - pip install --user --upgrade conan
  # Automatic detection of your arch, compiler, etc.
  - conan user && conan config set compiler.libcxx=libstdc++11
  # install ninja build
  - sudo apt-get -y install ninja-build

script:
  - mkdir build && cd build
  - conan install ../ --build=missing -s compiler.libcxx=libstdc++11
  - cmake -G Ninja ..
  - build-wrapper-linux-x86-64 --out-dir sonar-build cmake --build .
  - ctest
  - sonar-scanner
