dist: bionic
sudo: false
language: cpp

compiler:
  - gcc

install:
  # use latest CMake
  - |
    if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
      DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
      CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v3.16.3/cmake-3.16.3-Linux-x86_64.tar.gz"
      mkdir -p ${DEPS_DIR}/cmake
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi
  # Install conan
  - pip install --user --upgrade conan
  # Automatic detection of your arch, compiler, etc.
  - conan user && conan config set compiler.libcxx=libstdc++11

script:
  - mkdir build && cd build
  - conan install ../ --build=missing -s compiler.libcxx=libstdc++11
  - cmake -G Ninja ..
  - cmake --build .
  - ctest
