---
version: 1.0.{build}

image:
  - Visual Studio 2019

environment:
  matrix:
    - configuration: "Debug"
      env_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/vcvars64.bat"
      runtime: "MDd"
    - configuration: "Release"
      env_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/vcvars64.bat"
      runtime: "MD"

install:
  - cmd: >-
      set PATH=%PYTHON%/Scripts/;%PATH%

      pip.exe install --upgrade conan==1.27.1

      conan user

build_script:
  - cmd: >-
      call "%env_script%"

      set PATH=%PYTHON%/Scripts/;%PATH%

      mkdir build && cd build

      conan install .. --settings build_type=Release --settings compiler.runtime=%runtime% --build

      cmake ../ -G "Ninja" -DCMAKE_BUILD_TYPE=%configuration%

      cmake --build . --config %configuration%

test_script:
  - ctest -C %configuration%
