---
version: 1.0.{build}

image:
  - Visual Studio 2017
  - Visual Studio 2019

platform:
  - x64

configuration:
  - Debug
  - Release

environment:
  matrix:
    - image: Visual Studio 2017
      CMAKE_GENERATOR: "Visual Studio 15 2017"

    - image: Visual Studio 2019
      CMAKE_GENERATOR: "Visual Studio 16 2019"

install:
  - set PATH=%PYTHON%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - conan user
  - mkdir build
  - cd build

build_script:
  - set PATH=%PYTHON%/Scripts/;%PATH%
  - conan install .. --settings build_type=%CONFIGURATION% --build=missing
  - cmake ../ -G %CMAKE_GENERATOR% -A x64
  - cmake --build . --config %CONFIGURATION%  -- -verbosity:minimal

test_script:
  - ctest -C %CONFIGURATION%
