---
version: 1.0.{build}

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Debug
  - Release

install:
  - set PATH=%PYTHON%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - conan user
  - mkdir build
  - cd build

build_script:
  - set PATH=%PYTHON%/Scripts/;%PATH%
  - conan install .. --settings build_type=%CONFIGURATION% --build=missing
  - cmake ../ -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=%CONFIGURATION%
  - cmake --build . --config %CONFIGURATION%  -- -verbosity:minimal

test_script:
  - ctest -C %CONFIGURATION%
