version: 2
jobs:
  build:
    working_directory: ~/cardshuffler
    docker:
      - image: conanio/gcc8
    steps:
      - checkout
      - run:
          name: "Install build dependencies"
          command: |
            sudo apt-get update -q
            sudo apt-get install -y -q unzip
            pip -q install --user --upgrade conan
            wget -nv https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
            unzip -qq build-wrapper-linux-x86.zip
            sudo mv build-wrapper-linux-x86/* /usr/local/bin
            wget -nv https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip
            unzip -qq sonar-scanner-cli-4.2.0.1873-linux.zip -d ../
      - run:
          name: "Setup Conan"
          command: |
            conan user
            conan profile new --detect --force default
            conan profile update settings.compiler.libcxx=libstdc++11 default
      - run:
          name: "Install Conan Packages"
          command: |
            mkdir -p build/sonar
            cd build
            conan install .. --build=missing
      - run:
          name: "CMake"
          command: |
            cd build
            cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_COVERAGE=ON -G Ninja ..
      - run:
          name: "Build"
          command: "VERBOSE=1 build-wrapper-linux-x86-64 --out-dir sonar cmake --build build/ --target all"
      - run:
          name: "Test"
          command: "cmake --build build --target test"
      - run:
          name: "Code Coverage"
          command: "curl -s https://codecov.io/bash | sed 's/-execdir $gcov_exe/-exec $gcov_exe/' | bash -s -- -x /usr/bin/gcov-8"
      - run:
          name: "Sonar Scan"
          command: "~/sonar-scanner-4.2.0.1873-linux/bin/sonar-scanner"
      - store_test_results:
          path: build/tests/results

