version: 2
jobs:
  build:
    working_directory: ~/cardshuffler
    docker:
      - image: conanio/gcc8
    steps:
      - checkout
      - run:
          name: "Install build dependencies"
          command: "pip install --user --upgrade conan;
            conan user;
            conan profile new --detect --force default;
            conan profile update settings.compiler.libcxx=libstdc++11 default"
      - run:
          name: "Build Environment"
          command: "gcc --version
            g++ --version;
            cmake --version;
            conan --version;"
      - run:
          name: "Build"
          command: "mkdir build;
          cd build;
          conan install .. --build=missing;
          cmake .. -DCMAKE_BUILD_TYPE=Debug;
          cmake --build . --target all -- -j4"
      - run:
          name: "Test"
          command: "cmake --build build --target test"
