version: 2
jobs:
  docker:
    - image: conanio/gcc8
  steps:
    - checkout
    - run:
        name: Build Conan package
        command: |
          sudo pip install --upgrade conan
          conan user
    - run:
        name: Build and Test
        command: |
          pwd
          gcc --version
          g++ --version
          cmake --version
          conan --version
          mkdir build
          cd build && conan install .. --build=missing
          cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug
          cmake --build build --target all -- -j4
          cmake --build build --target test
workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc
